name: Swift Package Manager Release
on:
  workflow_call:
    inputs:
      tag:
        description: 'The SDK version to release, ex: 0.9.97'
        required: true
        type: string
jobs: 
  verify-version:
    name: Say Hello
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello"
