name: Release GitHub
on:
  workflow_call:
    inputs:
      version:
        description: 'The SDK version to release, ex: 0.9.113'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: 'The SDK version to release, ex: 0.9.113'
        required: true
        type: string
jobs: 
  generate-package-swift:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Create GitHub Release
        id: create-gh-release
        run: |
          gh release create "${{ inputs.version }}" \
            --target "$GITHUB_REF_NAME" \
            --title "${{ inputs.version }}"
        env:
          GH_TOKEN: ${{ github.token }}
