name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  version-change:
    name: Check for version change
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.check.outputs.version }}
      version_changed: ${{ steps.check.outputs.version_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check
        id: check
        run: |
          if ! git diff --exit-code HEAD~1 HEAD .version; then
            echo "Detected changes..."
            echo "version=\"$(cat .version)\"" >> $GITHUB_ENV
            echo "version_changed=true" >> $GITHUB_OUTPUT
          fi
  # This effectively releases a new Swift Package Manager version
  create-github-release:
    uses: ./.github/workflows/release_gh.yaml
    with:
      version: ${{ needs.version-change.outputs.version }}
    permissions:
      contents: write
    needs: version-change
    if: needs.version-change.outputs.version_changed == 'true'
    secrets: inherit
  release-cocoapods:
    uses: ./.github/workflows/release_cocoapods.yaml
    needs: create-github-release
    secrets: inherit
