name: Release CocoaPods
on:
  workflow_call:
  workflow_dispatch:
jobs:
  release-cocoapods:
    name: Publish CocoaPods specs
    environment: release-cocoapods
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up CI
        run: ./tools/ci/mac_ci_setup.sh
      - name: Publish CocoaPods specs
        run: ./tools/ci/release_cocoapods.sh
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
