name: Release CocoaPods
on:
  workflow_call:
  workflow_dispatch:
jobs:
  release-cocoapods:
    name: Publish CocoaPods specs
    environment: release-cocoapods
    runs-on: macos-13
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up CI
        run: ./ci/mac_ci_setup.sh
      - name: Publish CocoaPods specs
        run: /ci/release_cocoapods.sh
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
