name: Tests
on:
  push:
    branches:
      - main
  pull_request:
# Cancel in-progress CI jobs when a new commit is pushed to a PR.
concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true
jobs: 
  tests:
    name: Run Tests
    runs-on: macos-latest
    steps:
      - name: Run Tests
        run: xcodebuild test -scheme Capture  -sdk iphonesimulator17.0 -destination "OS=17.0,name=iPhone 15"

