name: tests
on:
  push:
    branches:
      - main
  pull_request:
# Cancel in-progress CI jobs when a new commit is pushed to a PR.
concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true
jobs:
  tests:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Set up CI
        run: | # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode
          sudo xcode-select --switch /Applications/Xcode_15.0.app
      - name: Run Tests
        run:  |
          xcodebuild \
          -scheme Capture \
          -sdk iphonesimulator17.0 \
          -destination 'platform=iOS Simulator,OS=latest,name=iPhone 15' \
          test
