name: tests
on:
  push:
    branches:
      - main
  pull_request:
# Cancel in-progress CI jobs when a new commit is pushed to a PR.
concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true
jobs:
  tests:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Set up CI
        run: ./ci/mac_ci_setup.sh
      - name: Run Tests
        run:  |
          xcodebuild \
          -scheme Capture \
          -sdk iphonesimulator17.2 \
          -destination 'platform=iOS Simulator,OS=latest,name=iPhone 15' \
          test
