name: Verify CocoaPods
on:
    push:
      branches:
        - main
    pull_request:
jobs:
  release-cocoapods:
    name: Trial CocoaPods specs push
    environment: release-cocoapods
    runs-on: macos-13
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up CI
        # Use Xcode 14.3.1 as Xcode 15 doesn't support iOS 11 and this is a minimal deployment target supported by Cocoalumberjack.
        # See https://github.com/CocoaPods/CocoaPods/issues/11839 for more details.
        # TODO(Augustyniak): Move to Xcode 15 once https://github.com/CocoaLumberjack/CocoaLumberjack/issues/1404 is resolved.
        run: sudo xcode-select --switch /Applications/Xcode_14.3.1.app
      - name: Push CocoaPods specs to local repo
        run: ./tools/ci/verify_cocoapods.sh
