name: CocoaPods
on:
    push:
      branches:
        - main
    pull_request:
jobs:
  verify-cocoapods:
    name: verify
    runs-on: macos-14
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up CI
        run: ./tools/ci/mac_ci_setup.sh
      - name: Verify CocoaPods specs
        run: make verify
